{"uuid": "dc530eef-bf7f-43fa-abe9-5495a1d2df6f", "children": ["ca494be2-507e-4ff2-b976-7e31456b61c3"], "befores": [{"name": "data_test", "status": "broken", "statusDetails": {"message": "OSError: [Errno 22] Invalid argument: '../data_test/data_C:\\\\Users\\\\Sabri\\\\Documents\\\\AUTOMATION\\\\demo_casino\\\\tests.yaml'\n", "trace": "  File \"C:\\Users\\Sabri\\Documents\\AUTOMATION\\demo_casino\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Sabri\\Documents\\AUTOMATION\\demo_casino\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Sabri\\Documents\\AUTOMATION\\demo_casino\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 900, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Sabri\\Documents\\AUTOMATION\\demo_casino\\tests\\conftest.py\", line 9, in data_test\n    return FileUtils.get_yaml_data(f\"../data_test/data_{test_filename}.yaml\")\n  File \"C:\\Users\\Sabri\\Documents\\AUTOMATION\\demo_casino\\utilities\\file_utils.py\", line 8, in get_yaml_data\n    with open(file_path, \"r\", encoding='utf-8') as f:\n"}, "start": 1663166667502, "stop": 1663166667502}], "start": 1663166667502, "stop": 1663166670198}